apiVersion: v1
kind: Service
metadata:
  name: egovframe-boot-sample-java-config
spec:
  type: NodePort
  selector:
    app: egovframe-boot-sample-java-config
  ports:
  - protocol: TCP
    port: 8080
    targetPort: web
    nodePort: 30200
