apiVersion: v1
kind: Service
metadata:
  name: eegovframe-web-sample
spec:
  type: NodePort
  selector:
    app: egovframe-web-sample
  ports:
  - protocol: TCP
    port: 8080
    targetPort: web
    nodePort: 30100
